### ISSUE TITLE
fork, release from agoric-labs

### ISSUE THREAD

**Issue by dckc** [dckc/tape-xs#5]
This should fork from https://github.com/agoric-labs/tape-xs , not the other way around

alternatives:

 - transfer this repository to agoric-labs (after we rename the current agoric-labs/tape-xs)
 - delete this one and fork from agoric-labs/tape-xs

cc @michaelfig

**Comment by michaelfig** [comment]
Can you do the transfer?  If not possible to transfer with the same name, please rename it (like `tape-xs-orig`), and then I can shuffle them around.

**Comment by dckc** [comment]
No, evidently I cannot; I get:
> agoric-labs already has a repository in the dckc/tape-xs-orig network and You don’t have the permission to create public repositories on agoric-labs

**Comment by michaelfig** [comment]
Can you add me as a collaborator with admin rights?  Then I should be able to move things around.

**Comment by dckc** [comment]
I added you as a collaborator, but I don't see an option for admin rights.

**Comment by michaelfig** [comment]
When #4 is merged (or a workalike), I'll be ready to delete the agoric-labs/tape-xs fork, as it won't have any more state.  Then we can work out how to transfer this repo to that org.

**Comment by dckc** [comment]
whee! done.

**Comment by dckc** [comment]
The latest release, [ag03][3] is on a branch that seems to conflict with master. I'm not quite clear on how to straighten this out.

[3]: https://github.com/agoric-labs/tape-xs/releases/tag/ag03

**Comment by michaelfig** [comment]
The branch is an orphan.  Current master is at least as functional, so development should continue on master.
